Repository AY2324S1-CS2103-F13-4/tp, pull requests merged in 2023-11, with the labels that each got.

#72 Add author tags to DG
  docs/DeveloperGuide.md
Labels: documentation

#76 Implement Delete Task Command
  src/main/java/seedu/address/logic/commands/DeleteTaskCommand.java
  src/main/java/seedu/address/logic/parser/DeleteTaskCommandParser.java
  src/main/java/seedu/address/logic/parser/UniMateParser.java
  src/main/java/seedu/address/model/task/TaskList.java
  src/test/java/seedu/address/logic/commands/DeleteTaskCommandTest.java
  src/test/java/seedu/address/logic/parser/DeleteTaskCommandParserTest.java
  src/test/java/seedu/address/logic/parser/UniMateParserTest.java
  src/test/java/seedu/address/model/task/TaskManagerTest.java
Labels: enhancement

#70 [Calendar] Calendar Comparison
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/CompareCalendarByIndexCommand.java
  src/main/java/seedu/address/logic/commands/CompareCalendarByTagCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/SwitchListCommand.java
  src/main/java/seedu/address/logic/parser/CompareCalendarByIndexCommandParser.java
  src/main/java/seedu/address/logic/parser/CompareCalendarByTagCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/UniMateParser.java
  src/main/java/seedu/address/logic/parser/exceptions/RuntimeParseException.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/calendar/UniMateCalendar.java
  src/main/java/seedu/address/model/event/AllDaysEventListManager.java
  src/main/java/seedu/address/model/event/EventPeriod.java
  src/main/java/seedu/address/model/event/SingleDayEventList.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleCalendarUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonSerializableCalendar.java
  src/main/java/seedu/address/ui/CalendarContainer.java
  src/main/java/seedu/address/ui/CalendarEventSpace.java
  src/main/java/seedu/address/ui/EventSpaceBackground.java
  src/main/java/seedu/address/ui/EventSpaceBackgroundColumn.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/UiConstants.java
  src/main/resources/view/CalendarContainer.fxml
  src/main/resources/view/EventSpaceBackground.fxml
  src/main/resources/view/EventSpaceBackgroundColumn.fxml
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddEventCommandTest.java
  src/test/java/seedu/address/logic/commands/AddTaskCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearEventsCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/logic/commands/DeleteEventCommandTest.java
  src/test/java/seedu/address/logic/commands/ExitCommandTest.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/calendar/CalendarTest.java
  src/test/java/seedu/address/storage/JsonCalendarStorageTest.java
  src/test/java/seedu/address/storage/JsonSerializableCalendarTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/testutil/CalendarBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalEvents.java
Labels: enhancement

#86 Update UG
  docs/UserGuide.md
  src/main/resources/view/MainWindow.fxml
Labels: documentation

#153 Update PPP for Nicholas Lee
  docs/team/nicrandomlee.md
Labels: documentation

#154 Update HG Draft PPP
  docs/team/lihongguang00.md
Labels: documentation

#150 Bug Fixing 1
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/ClearEventsCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/event/EventPeriod.java
  src/main/java/seedu/address/model/event/exceptions/InvalidEventPeriodException.java
  src/main/java/seedu/address/model/task/Deadline.java
  src/main/java/seedu/address/model/task/TaskDescription.java
  src/main/java/seedu/address/model/task/exceptions/InvalidDeadlineException.java
  src/test/java/seedu/address/model/event/EventPeriodTest.java
  src/test/java/seedu/address/model/task/DeadlineTest.java
  src/test/java/seedu/address/storage/JsonAdaptedEventTest.java
Labels: bug, documentation

#158 UG Improvements
  docs/UserGuide.md
Labels: documentation

#159 Fix minor error
  docs/UserGuide.md
Labels: documentation

#160 Update UG
  docs/UserGuide.md
  docs/images/addCommand.png
  docs/images/addContactEventCommand.png
  docs/images/addEventCommand.png
  docs/images/addTaskCommand.png
  docs/images/calendarUI.png
  docs/images/clearCommand.png
  docs/images/clearEventsCommand.png
  docs/images/compareCalendarsCommand.png
  docs/images/compareGroupCalendarsCommand.png
  docs/images/contactCalendar.png
  docs/images/deleteCommand.png
  docs/images/deleteContactEventCommand.png
  docs/images/deleteEventCommand.png
  docs/images/deleteTaskCommand.png
  docs/images/editCommand.png
  docs/images/editContactEventCommandAfter.png
  docs/images/editContactEventCommandBefore.png
  docs/images/editContactEventCommandMessage.png
  docs/images/eventList.png
  docs/images/filterCommand.png
  docs/images/findCommand.png
  docs/images/helpMessage.png
  docs/images/listCommand.png
  docs/images/sortCommand.png
  docs/images/sortTasksCommand.png
  docs/images/switchListCommand.png
  docs/images/uniMateFeatures.png
  docs/images/unimateScreenshot.png
  docs/images/viewContactEventsCommand.png
Labels: documentation

#151 Branch bug fixes
  src/main/resources/view/EventListPanel.fxml
Labels: bug

#163 Fix bugs
  src/main/java/seedu/address/logic/commands/CompareCalendarByIndexCommand.java
  src/main/java/seedu/address/logic/commands/CompareCalendarByTagCommand.java
  src/main/java/seedu/address/logic/parser/CompareCalendarByIndexCommandParser.java
  src/main/java/seedu/address/logic/parser/CompareCalendarByTagCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
Labels: bug
