Repository AY2324S1-CS2103-F13-4/tp, pull requests merged in 2023-10, with the labels that each got.

#22 Add DG for Week 7 tP task
  docs/AboutUs.md
  docs/DeveloperGuide.md
  src/main/java/seedu/address/calendar/temp.txt
Labels: documentation

#30 Add Hongguang Skeletal PPP
  docs/AboutUs.md
  docs/team/lihongguang00.md
Labels: documentation

#36 Add filter command
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/FilterCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/FilterCommandTest.java
  src/test/java/seedu/address/logic/commands/PersonFilterTest.java
  src/test/java/seedu/address/logic/parser/FilterCommandParserTest.java
  src/test/java/seedu/address/testutil/PersonFilterBuilder.java
Labels: enhancement

#40 Add Sort Function
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/parser/UniMateParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddEventCommandTest.java
  src/test/java/seedu/address/logic/commands/SortCommandTest.java
  src/test/java/seedu/address/logic/parser/UniMateParserTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: enhancement

#42 Add calendar storage functionality
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/calendar/Calendar.java
  src/main/java/seedu/address/model/calendar/ReadOnlyCalendar.java
  src/main/java/seedu/address/model/event/AllDaysEventListManager.java
  src/main/java/seedu/address/model/event/EventPeriod.java
  src/main/java/seedu/address/model/util/SampleCalendarUtil.java
  src/main/java/seedu/address/storage/CalendarStorage.java
  src/main/java/seedu/address/storage/JsonAdaptedEvent.java
  src/main/java/seedu/address/storage/JsonCalendarStorage.java
  src/main/java/seedu/address/storage/JsonSerializableCalendar.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/test/data/JsonCalendarStorageTest/invalidAndValidEventCalendar.json
  src/test/data/JsonCalendarStorageTest/invalidEventCalendar.json
  src/test/data/JsonCalendarStorageTest/notJsonFormatCalendar.json
  src/test/data/JsonSerializableCalendarTest/duplicateEventCalendar.json
  src/test/data/JsonSerializableCalendarTest/invalidEventCalendar.json
  src/test/data/JsonSerializableCalendarTest/typicalEventsCalendar.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddEventCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteEventCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/FilterCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/commands/SortCommandTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/UserPrefsTest.java
  src/test/java/seedu/address/storage/JsonAdaptedEventTest.java
  src/test/java/seedu/address/storage/JsonCalendarStorageTest.java
  src/test/java/seedu/address/storage/JsonSerializableCalendarTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/testutil/CalendarBuilder.java
  src/test/java/seedu/address/testutil/TypicalEvents.java
Labels: enhancement

#52 Update DG for Fiilter and DeleteEvent commands
  docs/DeveloperGuide.md
Labels: documentation

#53 Update DG for AddEvent command
  docs/DeveloperGuide.md
Labels: documentation

#63 [Calendar] Improved Calendar UI
  .codecov.yml
  build.gradle
  src/main/java/seedu/address/Main.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/calendar/Calendar.java
  src/main/java/seedu/address/model/calendar/ReadOnlyCalendar.java
  src/main/java/seedu/address/model/event/AllDaysEventListManager.java
  src/main/java/seedu/address/model/event/Event.java
  src/main/java/seedu/address/model/event/EventPeriod.java
  src/main/java/seedu/address/model/event/SingleDayEventList.java
  src/main/java/seedu/address/model/event/exceptions/DateOutOfBoundsException.java
  src/main/java/seedu/address/storage/JsonAdaptedEvent.java
  src/main/java/seedu/address/storage/JsonSerializableCalendar.java
  src/main/java/seedu/address/ui/CalendarContainer.java
  src/main/java/seedu/address/ui/CalendarEventSpace.java
  src/main/java/seedu/address/ui/CalendarLabelColumn.java
  src/main/java/seedu/address/ui/EventSpaceBackground.java
  src/main/java/seedu/address/ui/EventSpaceBackgroundColumn.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/CalendarContainer.fxml
  src/main/resources/view/CalendarEventSpace.fxml
  src/main/resources/view/CalendarLabelColumn.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/EventSpaceBackground.fxml
  src/main/resources/view/EventSpaceBackgroundColumn.fxml
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddEventCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteEventCommandTest.java
  src/test/java/seedu/address/logic/parser/UniMateParserTest.java
  src/test/java/seedu/address/model/calendar/CalendarTest.java
  src/test/java/seedu/address/model/event/EventTest.java
  src/test/java/seedu/address/storage/JsonAdaptedEventTest.java
  src/test/java/seedu/address/testutil/EventBuilder.java
Labels: enhancement

#65 Add the ability to allow contacts to have events (Contact calendar)
  src/main/java/seedu/address/logic/commands/AddContactEventCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddContactEventCommandParser.java
  src/main/java/seedu/address/logic/parser/UniMateParser.java
  src/main/java/seedu/address/model/person/Person.java
  src/test/java/seedu/address/logic/commands/AddContactEventCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddContactEventCommandParserTest.java
  src/test/java/seedu/address/logic/parser/UniMateParserTest.java
Labels: enhancement

#66 Update Sort Function
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
  src/test/java/seedu/address/logic/parser/SortCommandParserTest.java
Labels: bug, documentation

#67 Add Person Calendar UI
  src/main/java/seedu/address/ui/CalendarContainer.java
  src/main/java/seedu/address/ui/CalendarEventSpace.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/CalendarContainer.fxml
  src/main/resources/view/EventSpaceBackground.fxml
  src/main/resources/view/EventSpaceBackgroundColumn.fxml
Labels: enhancement

#69 [Calendar] Calendar UI Bug Fixes
  src/main/java/seedu/address/model/event/Event.java
  src/main/java/seedu/address/model/event/EventPeriod.java
  src/main/java/seedu/address/ui/CalendarContainer.java
  src/main/java/seedu/address/ui/CalendarEventSpace.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/CalendarContainer.fxml
  src/main/resources/view/EventSpaceBackgroundColumn.fxml
  src/test/java/seedu/address/model/event/EventPeriodTest.java
Labels: bug
